# -*- coding: utf-8 -*-
print "Hello........how are you?"
print "It's been a thousand years."
print "Dance like you mean it \n"
print "Kill the noise...... Roc Nation"
print "Print monica....scratch that my nigga"
print "If I loose myself tonight, it will be by your side"
print "black denims I'm in suvies nigga, I dont shop at SAX"
print "Ring the alarm, smoke the fucking cigar"
print "Settle down, i Will always be here"
print "I'm gonna make this place my home"